# Generated by Django 4.2.6 on 2023-10-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='school_id',
            new_name='school',
        ),
    ]
