# Generated by Django 4.2.6 on 2023-10-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hz', '0002_rename_school_id_teacher_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
    ]
