# Generated by Django 4.2.6 on 2023-10-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hz', '0003_alter_school_options_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='Полное наименование'),
        ),
    ]
